### PR TITLE
tests for models package <testing

### PR DESCRIPTION
**Pull request by Fleaxes**

### CODE REVIEW

**Comment by martijnjanssen** [comment]
The code looks fine, but why are there so much asserts in one test method?! A test only needs to test one thing only. For instance the testCreateIndicator test has to only check whether a new indicator is created. The name of the test has to specify what is tested. Also a test should only test ONE thing and ONE thing only. Please change this. <organization

**Comment by Fleaxes** [comment]
Deleted the extra asserts and a non-used package import line. Build passes again

**Comment by ric-jon** [comment]
Code looks good. However, the deleted asserts shouldn't have been deleted necessarily, just moved into seperate methods so that every test method has as few asserts as possible. This is to avoid having a test method fail when only one of the asserts fails.

**Comment by lenigoor** [comment]
I agree about rather moving assertions to a new method instead of deleting them. Also, why are there in the test case for the Player class two methods commented out?

**Comment by Fleaxes** [comment]
That is indeed a good option, I will change that. 
The reason why two methods are commented out is because I was having problems because these two methods indirectly use opengl, so we need to find a different solution on testing these two.

**Comment by ric-jon** [comment]
Code looks great now, everything is still being tested but in separate methods! Ready to merge

**Pull request merged**
