### PR TITLE
Findbugs

### PR DESCRIPTION
**Pull request by martijnjanssen**
Resolved a lot of findbug issues. We still need to fix 5 more.

### CODE REVIEW

**Comment by lenigoor** [comment]
I like the changes, renaming these methods to start without an uppercase letter is more confirm the standard Java syntax. In the `Player` class I found that there still exists a field called `playerMass`. This field is obsolete and should be removed, can you fix that in this branch?

**Comment by MilleIT** [comment]
actually leon, it should not be removed as it is still in use.

**Comment by lenigoor** [comment]
In the `NonPlayer` class I can still find a '<<<<<<< HEAD' tag, please fix this. Also, the class description comment on top of the `MousePosition` and `DrawPosition` class doesn't make sense anymore. Could you revert these two comments to their previous values?

**Comment by lenigoor** [comment]
Awesome, thanks for making these changes! Merging.

**Pull request merged**
