### PR TITLE
Remove code smells reported by InCode <layout,naming,logic

### PR DESCRIPTION
**Pull request by lenigoor**
The InCode code smell reporting tool found some problems in our code. The found code smells were 'Data Clumb', 'Data Class' and 'Feature Envy'. This branch fixes those problems by refactoring code.

### CODE REVIEW

**Comment by MilleIT** [comment]
maybe data is a little too generic name
could change it to movedata or something.

**Comment by lenigoor** [comment]
Yea I could change it to movedata, but at the places where it is referenced the name will be longer. So I deliberately made my choice to keep it simple and thus use the name `data`.

**Comment by Fleaxes** [comment]
It seems like something goes wrong with BigOpponentTest and thus the build fails, maybe try to merge development back into this branch and then see if the build still fails

**Comment by Fleaxes** [comment]
Great! The build does not fail anymore! Can be merged

**Pull request merged**
