### PR TITLE
sprint plan and reflection <documentation

### PR DESCRIPTION
**Pull request by Fleaxes**
Sprint Reflection #2 and Sprint Plan #3

### CODE REVIEW

**Comment by martijnjanssen** [comment]
We can't read the contents of the document, could you upload a text document next time?

**Comment by lenigoor** [comment]
Please update the sprint plan to include the UML exercises and assign them to someone of our team.

**Comment by Fleaxes** [comment]
Added the UML to the sprintplan.
The assignment wants the file to be a pdf, if you want to read the contents you can see it in the branch

**Comment by MilleIT** [comment]
you could upload the text document before converting it to pdf next time

**Comment by lenigoor** [comment]
I don't agree with uploading text documents, just pull and view it locally. Uploading duplicates will clutter our repository.

**Pull request merged**
