### PR TITLE
Feature powerup cleanup

### PR DESCRIPTION
**Pull request by MilleIT**
fixed the shield powerup images, tweaked some parameters and wrote some tests for poison and shield.

### CODE REVIEW

**Comment by ric-jon** [comment]
Try to not forget javadoc for newly created methods so others know what it does, and we don't have to come back to it later.

**Comment by lenigoor** [comment]
You should consider moving the timer logic into a more generic timer class, so the power-up specific timer behaviour can be stored in the appropriate power-up class. Right now the Player class has too many responsibilities and is getting clogged.

**Comment by lenigoor** [comment]
Also, please merge development into this branch so GitHub can merge the pull-request automatically when it's time to do so.

**Comment by lenigoor** [comment]
After some testing, it seems that calling `eat()` each time inside the `updateImage(String key)` in the `Player` class writes an entry to the log file which limits the framerate around 20 FPS. I can't play the game anymore. I will fix this in a diferent branch, because this one is already merged.

**Pull request merged**
